obj-y := \
	memcpy.o \
	memmove.o \
	memset.o \
	memcmp.o \
	memchr.o \
	strcpy.o \
	strncpy.o \
	strcat.o \
	strncat.o \
	strcmp.o \
	strncmp.o \
	strcoll.o \
	strxfrm.o \
	strchr.o \
	strrchr.o \
	strcspn.o \
	strspn.o \
	strpbrk.o \
	strstr.o \
	stpcpy.o \
	stpncpy.o \
	strchrnul.o \
	memrchr.o
