#!/usr/bin/env python
import os, sys
from kconfiglib import Kconfig
from menuconfig import menuconfig

def mconf_set_env(style, conf, header):
	"""
	Set Kconfig Env
	"""
	os.environ["MENUCONFIG_STYLE"] = style
	os.environ["KCONFIG_CONFIG"] = conf
	os.environ["KCONFIG_CONFIG_HEADER"] = header
	os.environ["KCONFIG_AUTOHEADER"] = os.path.join("menuconfig.h")
	os.environ["CONFIG_"] = ""

def mconfig(argv):
	try:
		display_style = "default selection=fg:white,bg:blue"
		target_conf = os.path.join(".config")
		header = "# Generated by Light Weight Kconfig Tool"
		mconf_set_env(display_style, target_conf, header)
		kconfig = os.path.join("config", "../config/config.in")
		kconf = Kconfig(filename=kconfig)
		if len(argv) == 3 and argv[1] == 'defconfig':
			kconf.load_config(argv[2])
			print(kconf.write_config()) 	# defconfig
		else:
			if os.path.exists(target_conf):
				kconf.load_config(target_conf)
			menuconfig(kconf)
		kconf.write_config(".config")
	except Exception as e:
		print(f"Error: {e}")
		sys.exit(1)

if __name__ == "__main__":
	mconfig(sys.argv)
