ifeq ($(CONFIG_COMPILER_OPTIMIZE_NONE), y)
	CFLAGS += -O0
endif

ifeq ($(CONFIG_COMPILER_OPTIMIZE_SPEED), y)
	CFLAGS += -O2
endif

ifeq ($(CONFIG_COMPILER_OPTIMIZE_SIZE), y)
	CFLAGS += -Os
endif

CFLAGS += -g -Wall -Werror -fno-builtin -nostdinc -nostdlib -pipe

CPPFLAGS += $(CFLAGS)

AFLAGS  += $(CFLAGS) -D__ASSEMBLY__

LDFLAGS = -static
