obj-y := \
	isalnum.o \
	isalpha.o \
	isblank.o \
	iscntrl.o \
	isdigit.o \
	isgraph.o \
	islower.o \
	isprint.o \
	ispunct.o \
	isspace.o \
	isupper.o \
	isxdigit.o \
	tolower.o \
	toupper.o \
	isascii.o \
	toascii.o

