obj-y := \
	printf.o \
	init.o \
	logo.o \
	tick.o \
	task.o \
	task_sched.o \
	mem_mgr.o \
	spin_lock.o \
	timeout.o \
	msgq.o \
	sem.o \
	mutex.o \
	log.o \
	percpu.o \
	kernel.o \
	timer.o \
	mem_domain.o \
	ring_buffer.o \
	fnmatch.o \
	heap.o

obj-$(CONFIG_SMP) += \
	smp.o

obj-$(CONFIG_USER_SPACE) += \
	syscall_dispatch.o \
	user_space.o

obj-$(CONFIG_SHELL) += \
	mem_domain_shell.o
