obj-y := string.o \
	printf.o \
	init.o \
	logo.o \
	tick.o \
	task.o \
	task_sched.o \
	mem_mgr.o \
	spin_lock.o \
	timeout.o \
	msgq.o \
	sem.o \
	mutex.o \
	log.o \
	percpu.o \
	kernel.o \
	timer.o \
	mem_domain.o

obj-$(CONFIG_SMP) += \
	smp.o

obj-$(CONFIG_USER_SPACE) += \
	syscall_dispatch.o \
	syscall.o

