obj-y := vector.o \
	exception.o \
	switch.o \
	operate_regs.o \
	mmu.o \
	kernel_map.o \
	head.o \
	isr.o

obj-$(CONFIG_GIC_V2) += gic_v2.o \
	isr_table.o \
	irq.o

obj-$(CONFIG_FPU_ENABLE) += fpu.o

