obj-y := vector.o \
	exception.o \
	switch.o \
	operate_regs.o \
	mmu.o \
	kernel_map.o \
	head.o \
	isr.o \
	arch_timer.o \
	cpu.o \
	arch_task.o \
	stack_trace.o \
	arch_spinlock.o \
	cache.o \
	tlb.o \
	smccc.o \
	cpu_ops_psci.o \
	sync_exc.o \
	arch_mem_domain.o

obj-$(CONFIG_GIC_V2) += gic_v2.o \
	isr_table.o \
	irq.o

obj-$(CONFIG_FPU_ENABLE) += fpu.o

obj-$(CONFIG_SMP) += arch_smp.o \
	arch_atomic.o

