obj-$(CONFIG_SAMPLE_USER_TASK) := sample_user_task.o
obj-$(CONFIG_SAMPLE_USER_MSGQ) := sample_user_msgq.o
obj-$(CONFIG_SAMPLE_USER_SEM) := sample_user_sem.o
obj-$(CONFIG_SAMPLE_USER_MUTEX) := sample_user_mutex.o