#ifndef __ARM64_TASK_OFFSETS_H__
#define __ARM64_TASK_OFFSETS_H__

#include <offsets.h>

#define ARCH_TASK_CONTEXT_X19_X20_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_X19_X20_OFFSET)
#define ARCH_TASK_CONTEXT_X21_X22_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_X21_X22_OFFSET)
#define ARCH_TASK_CONTEXT_X23_X24_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_X23_X24_OFFSET)
#define ARCH_TASK_CONTEXT_X25_X26_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_X25_X26_OFFSET)
#define ARCH_TASK_CONTEXT_X27_X28_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_X27_X28_OFFSET)
#define ARCH_TASK_CONTEXT_FP_LR_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_FP_LR_OFFSET)
#define ARCH_TASK_CONTEXT_SP_OFFSET \
	(TASK_CONTEXT_OF_CALLEE_CONTEXT_OFFSET + CALLEE_CONTEXT_OF_SP_OFFSET)
#define ARCH_TASK_FP_CONTEXT_OFFSET TASK_CONTEXT_OF_FP_CONTEXT_OFFSET

#endif
